services:  
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,s3,iam
      - DEBUG=1
      - PERSISTENCE=0              # No persistir datos
      - DISABLE_CORS_CHECKS=1      # Evitar problemas de CORS
    volumes:
      -  "/var/run/docker.sock:/var/run/docker.sock"  # Solo socket de Docker
    networks:
    - localstack_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant_poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_poc"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - localstack_network
    
  restaurant-api:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && sleep 10 && npm start"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=restaurant_poc
      - LOCAL_ID=RESTO_001
      - LOCAL_API_KEY=local-key-123
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure
    networks:
      - localstack_network

  restaurant-frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && sleep 5 && PORT=3001 REACT_APP_API_URL=http://restaurant-api:3000 npm start"
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://restaurant-api:3000
      - REACT_APP_API_KEY=local-key-123
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - restaurant-api
    volumes:
      - ./restaurant-frontend:/app
      - /app/node_modules
    restart: on-failure
    networks:
      - localstack_network

volumes:
  postgres_data:

networks:
  localstack_network:
    driver: bridge
